#!/bin/bash

if [ "$#" -ne 1 ]
then
	echo "Usage: ramdisk size_in_MB"
	exit 1
fi

if [[ $OSTYPE == *"linux"* ]]
then
	mkdir /mnt/ramdisk
	mount -t tmpfs -o size=$1m tmpfs /mnt/ramdisk
fi

if [[ $OSTYPE == *"darwin"* ]]
then
	diskutil erasevolume HFS+ 'RAM Disk' `hdiutil attach -nomount ram://$(($1*2048))`
fi
